name: Unit test for ARM
permissions:
  contents: read

on:
  push:
    branches:
      - main
      # Release branches
      - "[0-9]+.[0-9]+.X"
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.X"
  # Trigger the workflow on schedule
  schedule:
    # Nightly build at 2:45 A.M. (after Jammy build)
    - cron: "45 2 * * *"
  # Manual run
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check_skip:
    name: Check if job should be skipped
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check-skip.outputs.skip }}
      commit_message: ${{ steps.get-commit-message.outputs.message }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: get-commit-message
        name: Get commit message
        run: |
          echo "message=$(git log --format=%B -n 1 ${{ github.event.after || github.sha }} | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - id: check-skip
        name: Check if job should be skipped
        run: |
          if [[ "${{ steps.get-commit-message.outputs.message }}" =~ \[ci\ skip\] ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: check_skip
    if: needs.check_skip.outputs.skip != 'true' && github.repository == 'Agent-Benchmarking/scikit-learn'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install linters
        run: |
          source build_tools/shared.sh
          # Include pytest compatibility with mypy
          pip install pytest $(get_dep ruff min) $(get_dep mypy min) $(get_dep black min) cython-lint
      - name: Run linters
        run: ./build_tools/linting.sh
      - name: Run Meson OpenMP checks
        run: |
          pip install ninja meson scipy
          python build_tools/check-meson-openmp-dependencies.py

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-24.04-arm
    needs: [lint, jammy-build]
    if: |
      needs.check_skip.outputs.skip != 'true' &&
      github.repository == 'Agent-Benchmarking/scikit-learn' &&
      needs.jammy-build.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: build_tools/github/pymin_conda_forge_arm_linux-aarch64_conda.lock
          environment-name: ci
          cache-environment: true

      - name: Build and run tests
        shell: bash -el {0}
        run: bash build_tools/github/build_test_arm.sh

  # This job allows the workflow to complete even if the jammy-build job is skipped
  jammy-build:
    name: Depend on Jammy Build
    needs: check_skip
    if: needs.check_skip.outputs.skip != 'true' && github.repository == 'Agent-Benchmarking/scikit-learn'
    uses: ./.github/workflows/jammy-build.yml
