# Workflow to build and test wheels
name: CI Package Wheels

on:
  # Trigger the workflow on push or pull request on main branch or any release branch
  push:
    branches:
      - main
      - '[0-9]+.[0-9]+.X'
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.X'
  # Also trigger on workflow_dispatch
  workflow_dispatch:

# Set default permissions to read-only
permissions:
  contents: read
  issues: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_build_trigger:
    name: Check if workflow should be run
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.check.outputs.build }}
    steps:
      - name: Check if workflow should be run
        id: check
        env:
          # We run the full workflow for github.repository == scikit-learn/scikit-learn 
          # or the Agent-Benchmarking/scikit-learn repo
          REPO_NAME: ${{ github.repository }}
        run: |
          # Run if this is the main scikit-learn repo or the Agent-Benchmarking repo
          if [[ "$REPO_NAME" == "scikit-learn/scikit-learn" || "$REPO_NAME" == "Agent-Benchmarking/scikit-learn" ]]; then
            echo "build=true" >> $GITHUB_OUTPUT
            echo "::notice::Building on repository $REPO_NAME"
          else
            echo "build=false" >> $GITHUB_OUTPUT
            echo "::notice::Skipping build on fork repository $REPO_NAME"
          fi

  # This job checks if the ubuntu-builds workflow has completed
  check_ubuntu_builds:
    name: Check Ubuntu Builds
    needs: check_build_trigger
    if: needs.check_build_trigger.outputs.build == 'true'
    runs-on: ubuntu-latest
    outputs:
      ubuntu_build_status: ${{ steps.check_status.outputs.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Ubuntu Builds workflow status
        id: check_status
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = context.ref.replace('refs/heads/', '');
            
            // Look for the most recent run of the Ubuntu Builds workflow on this branch/PR
            const workflowName = "CI Ubuntu Tests";
            const workflows = await github.rest.actions.listRepoWorkflows({
              owner,
              repo
            });
            
            const ubuntuWorkflow = workflows.data.workflows.find(w => w.name === workflowName);
            if (!ubuntuWorkflow) {
              core.warning(`Could not find workflow: ${workflowName}. Will continue anyway.`);
              core.setOutput('status', 'not_found');
              return;
            }
            
            // Check for recent runs (completed, in progress, or queued)
            const runs = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: ubuntuWorkflow.id,
              branch: branch,
              per_page: 1
            });
            
            if (runs.data.total_count === 0) {
              core.notice(`No runs found for Ubuntu Builds workflow on branch '${branch}'`);
              core.setOutput('status', 'no_runs');
              return;
            }
            
            const latestRun = runs.data.workflow_runs[0];
            const status = latestRun.status;
            const conclusion = latestRun.conclusion;
            
            core.notice(`Latest Ubuntu Builds run: Status=${status}, Conclusion=${conclusion || 'N/A'}`);
            core.notice(`Run URL: ${latestRun.html_url}`);
            
            if (status === 'completed' && conclusion === 'success') {
              core.notice('Ubuntu Builds workflow completed successfully');
              core.setOutput('status', 'success');
            } else if (status === 'in_progress' || status === 'queued') {
              core.notice('Ubuntu Builds workflow is still running, will continue anyway');
              core.setOutput('status', 'in_progress');
            } else if (status === 'completed' && conclusion !== 'success') {
              core.warning('Ubuntu Builds workflow finished but did not succeed. Will continue anyway.');
              core.setOutput('status', 'failed');
            } else {
              core.warning(`Unexpected status: ${status}/${conclusion}`);
              core.setOutput('status', 'unknown');
            }

  # Build the wheels for Linux, Windows and macOS for Python 3.9 and newer
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.python }}
    needs: [check_build_trigger, check_ubuntu_builds]
    if: needs.check_build_trigger.outputs.build == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-13]
        python: [cp310, cp311, cp312]

    steps:
      - name: Display Ubuntu Builds Status
        run: |
          echo "Ubuntu Builds Status: ${{ needs.check_ubuntu_builds.outputs.ubuntu_build_status }}"
        shell: bash

      - name: Checkout scikit-learn
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Setup MSVC (Windows 64bit)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install OpenBLAS and other dependencies (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev gfortran

      - name: Build and test wheels and sdist
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: ${{ matrix.python }}-*
          CIBW_ARCHS: auto64
          CIBW_SKIP: "*musllinux*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_ENVIRONMENT: OMP_NUM_THREADS=2
                            OPENBLAS_NUM_THREADS=2
                            SKLEARN_SKIP_NETWORK_TESTS=1
                            SKLEARN_BUILD_PARALLEL=3
                            SKLEARN_MESON_OPTIONS="blas=openblas,lapack=openblas"
                            PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib64/pkgconfig
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
          CIBW_BEFORE_TEST: bash {project}/build_tools/wheels/cibw_before_test.sh
          CIBW_REPAIR_WHEEL_COMMAND: ""
          # Windows-specific configurations
          CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
          CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
          CIBW_TEST_REQUIRES_WINDOWS: ""
          CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
          # System-specific configurations
          CIBW_BEFORE_BUILD_LINUX: |
            if [ -f "/etc/redhat-release" ] || [ -f "/etc/centos-release" ]; then
              # For manylinux, use yum but with local repos only
              yum install -y --disablerepo=* --enablerepo=base,updates openblas-devel || echo "Could not install openblas-devel, will try to use pre-installed libraries"
            else
              # For Ubuntu/Debian systems
              apt-get update && apt-get install -y libopenblas-dev gfortran
            fi
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.15
          CIBW_BEFORE_ALL_MACOS: brew install libomp openblas
          CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS

          # Testing options
          # check because some architectures are emulated and tests would be too slow
          CIBW_TEST_SKIP: "*-macosx_arm64"
          CIBW_TEST_REQUIRES: pytest pandas threadpoolctl
          CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh {project}

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "sklearn-${{ matrix.python }}-${{ matrix.os }}"
          path: ./wheelhouse/*.whl

  # Build the wheels for PyPy 3.9 on Linux
  build_wheels_pypy:
    name: Build wheels on ubuntu-22.04 for PyPy
    needs: [check_build_trigger, check_ubuntu_builds]
    if: needs.check_build_trigger.outputs.build == 'true'
    runs-on: ubuntu-22.04
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        python: [pp310]

    steps:
      - name: Display Ubuntu Builds Status
        run: |
          echo "Ubuntu Builds Status: ${{ needs.check_ubuntu_builds.outputs.ubuntu_build_status }}"
        shell: bash

      - name: Checkout scikit-learn
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Install OpenBLAS and other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev gfortran

      - name: Build and test wheels and sdist
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: ${{ matrix.python }}-*
          CIBW_ARCHS: auto64
          CIBW_SKIP: "*musllinux*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_ENVIRONMENT: OMP_NUM_THREADS=2
                            OPENBLAS_NUM_THREADS=2
                            SKLEARN_SKIP_NETWORK_TESTS=1
                            SKLEARN_BUILD_PARALLEL=3
                            SKLEARN_MESON_OPTIONS="blas=openblas,lapack=openblas"
                            PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib64/pkgconfig
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD: bash {project}/build_tools/wheels/cibw_before_build.sh {project}
          CIBW_BEFORE_TEST: bash {project}/build_tools/wheels/cibw_before_test.sh
          CIBW_REPAIR_WHEEL_COMMAND: ""
          # Windows-specific configurations
          CIBW_CONFIG_SETTINGS_WINDOWS: "setup-args=--vsenv"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: bash build_tools/github/repair_windows_wheels.sh {wheel} {dest_dir}
          CIBW_BEFORE_TEST_WINDOWS: bash build_tools/github/build_minimal_windows_image.sh ${{ matrix.python }}
          CIBW_TEST_REQUIRES_WINDOWS: ""
          CIBW_TEST_COMMAND_WINDOWS: bash {project}/build_tools/github/test_windows_wheels.sh ${{ matrix.python }} {project}
          # System-specific configurations
          CIBW_BEFORE_BUILD_LINUX: |
            if [ -f "/etc/redhat-release" ] || [ -f "/etc/centos-release" ]; then
              # For manylinux, use yum but with local repos only
              yum install -y --disablerepo=* --enablerepo=base,updates openblas-devel || echo "Could not install openblas-devel, will try to use pre-installed libraries"
            else
              # For Ubuntu/Debian systems
              apt-get update && apt-get install -y libopenblas-dev gfortran
            fi
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.15
          CIBW_BEFORE_ALL_MACOS: brew install libomp openblas
          CIBW_ENVIRONMENT_PASS_LINUX: RUNNER_OS

          # Testing options
          CIBW_TEST_REQUIRES: pytest pandas threadpoolctl
          CIBW_TEST_COMMAND: bash {project}/build_tools/wheels/test_wheels.sh {project}

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "sklearn-${{ matrix.python }}-${{ matrix.os }}"
          path: ./wheelhouse/*.whl

  # Build the source distribution
  build_sdist:
    name: Source distribution
    needs: check_build_trigger
    if: needs.check_build_trigger.outputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout scikit-learn
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev gfortran
          python -m pip install --upgrade pip
          python -m pip install numpy cython build

      - name: Build source distribution
        run: |
          python -m build --sdist

      - name: Test install source distribution
        run: |
          mkdir tmp_for_test
          cd tmp_for_test
          pip install pytest numpy scipy threadpoolctl
          pip install ../dist/scikit-learn-*.tar.gz
          pytest --pyargs sklearn
          cd ..
          rm -rf tmp_for_test

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "sklearn-sdist"
          path: dist/scikit-learn-*.tar.gz
